name: Frontend Cloudfront Deployment

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Yarn Install
      run: yarn install

    - name: Yarn Build
      run: yarn build

    # - name: Deploy to S3
    #   run: |
    #     S3_BUCKET=s3://jmbl-cv-2023
    #     aws s3 sync ./out $S3_BUCKET --delete

    - name: S3 Deploy
      uses: lbertenasco/s3-deploy@v1
      with:
        folder: ./out
        bucket: S3_BUCKET=s3://jmbl-cv-2023
        dist-id: E19KBIZFPG78PP
        invalidation: /*

